authenticate/urls.py
from django.urls import path 
from . import views


app_name = "authenticate"

urlpatterns = [
    path("", views.empty, name="base"), 
    path("login/", views.login_user, name="login"), 
    path("signup/", views.signup_user, name="signup"), 
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url="auth/")), 
    path("auth/", include("authenticate.urls")), 
    path("stack/", include("stack.urls")), 
]

stack/urls.py
from django.urls import path 
from . import views


app_name = "stack"

urlpatterns = [
    path("ask/", views.ask_question, name="ask"),
    path("feed/", views.feed, name="feed"), 
    path("comments/<int:num>/",views.view_comments, name="comments"),
    path("posts/", views.user_posts, name="posts"), 
    path("delete/<int:id>/", views.delete_post, name="delete"), 
]

stack/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Create your models here.

class Questions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = RichTextField(blank=True, null = True)

    def __str__(self) -> str:
        return f"{self.user} asks {self.question}"

class Answers(models.Model):
    post = models.ForeignKey(Questions, on_delete=models.CASCADE)
    answer = RichTextField(blank=True, null = True)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.posted_by} answers {self.post.question} by saying {self.answer}"

stack/forms.py
from django import forms
from .models import Questions, Answers


class Question(forms.ModelForm):
    class Meta:
        model = Questions
        fields = ('question', )

        widgets = {
            'question': forms.Textarea(attrs={'class': 'form-control'}),	
        }

class Answer(forms.ModelForm):
    class Meta:
        model = Answers
        fields = ('answer', )

        widgets = {
            'answer':forms.Textarea(attrs={'class': 'form-control'}),	
        }

authenticate/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages

redirect_url = "stack:feed"
message = " have an account"

def empty(request):
    if request.user.is_authenticated:
        return redirect(reverse(redirect_url))
    return redirect(reverse("authenticate:login"))

def signup_user(request):
    if request.user.is_authenticated:
        return redirect(reverse(redirect_url))
    if request.POST:
        username = request.POST['username'].strip()
        password = request.POST['password']
        try:
            user = User.objects.create_user(username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse(redirect_url))
        except Exception:
            messages.add_message(request, messages.ERROR, "your username is already taken")
    return render(request, "auth.html", context={"title":"Signup", "message": message ,"final":"login", "login":False})

def login_user(request):
    if request.user.is_authenticated:
        return redirect(reverse(redirect_url))
    if request.POST:
        username = request.POST['username'].strip()
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse(redirect_url))
        else:
            messages.add_message(request, messages.ERROR, "your username or password is incorrect")

    return render(request, "auth.html", context={"title":"Login", "message": "don't " + message, "final": "signup", "login": True})

stack/views.py
from django.http import Http404
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from . models import Answers, Questions
from .forms import Question , Answer
# Create your views here.

login_redirect = "authenticate:login"

@login_required(login_url=login_redirect)
def ask_question(request):
    if "logout" in request.POST:
        logout(request)
        return redirect(reverse(login_redirect))
    if request.POST:
        question = request.POST['question']
        user = request.user 
        Questions.objects.create(question=question, user=user)
    
    form = Question

    return render(request, "ask.html", context={"title":"Ask", "form":form})


def feed(request):
    all_question = Questions.objects.all()[:10]
    if "logout" in request.POST:
        logout(request)
        return redirect(reverse(login_redirect))
    
    return render(request, "feed.html", context={"questions": all_question, "title":"feed"})


@login_required(login_url=login_redirect)
def view_comments(request, num):
    if "logout" in request.POST:
        logout(request)
        return redirect(reverse(login_redirect))
        
    try:
        post = Questions.objects.get(id=num)
    except Exception:
        raise Http404("The quesiton may be deleted")

    if request.POST:
        answer = request.POST["answer"]
        Answers.objects.create(posted_by=request.user, post=post, answer
        =answer)
    answers = Answers.objects.filter(post=post).all()

    form = Answer()
    
    return render(request, "view_comment.html", context={"title":"comments", "asked":post.user ,  "answers":answers, "form":form})

@login_required(login_url=login_redirect)
def user_posts(request):
    if "logout" in request.POST:
        logout(request)
        return redirect(reverse(login_redirect))
        
    posts = Questions.objects.filter(user=request.user).all()

    return render(request, "user_posts.html", context={"title":"Your post" , "questions":posts})

@login_required(login_url=login_redirect)
def delete_post(request, id):
    try:
        post = Questions.objects.get(pk=id)
    except Exception:
        raise Http404("The page you are searching for does not exist")
    see = True
    if post.user != request.user:
        see = False

    if "logout" in request.POST:
        logout(request)
        return redirect(reverse(login_redirect))
    
    elif request.POST:
        Questions.objects.get(pk=id).delete()
        return redirect(reverse("stack:posts"))

    return render(request, "delete.html", context={"post":post, "title":f"delete {post}", "see":see})

authenticate/templates/auth.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{{title}}</title>
    <style>
        .center {
            display: grid ;
            min-height: 80vh ;
            place-items: center ;
            align-content: center ;
            text-align: center;
        }

        input {
            margin-bottom: 3rem ;
            width: 50rem !important;
        }
        h1{
            margin-bottom: 1rem;
        }
    </style>
</head>
<body>
    <main class="center">
        <form method="post">
            {% csrf_token %}
            <h1>{{title}}</h1>
            <div class="auth-form">
                <input name="username" type="text" class="form-control" placeholder="Username" required>
                {% for message1 in messages %}
                    <small style="color: red;">{{message1}}</small><br>
                {% endfor %}
                {% if login %}
                    <small>{{message}} &nbsp;<a href="{% url 'authenticate:signup'%}">{{final}}</a></small>
               
                {% else %}
                    <small>{{message}} &nbsp;<a href="{% url 'authenticate:login' %}">{{final}}</a></small>
                {% endif %}
                <input name="password" class="form-control" type="password" placeholder="password" required>

                <button class="btn btn-primary">Enter</button>
            </div>
        </form>
    </main>
</body>
</html>

stack/templates/ask.html
{% extends 'sidebar.html' %} {% block sidebar %} {% load static %}
<link rel="stylesheet" href="{% static 'css/ask.css' %} " />
<section>
  <h1>Ask you question</h1>
  <form method="post">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <button class="btn btn-primary">Ask</button>
  </form>
</section>
{% endblock sidebar %}

stack/templates/delete.html
{% extends 'sidebar.html' %} {% block sidebar %} {% if see %}
<h1>are you sure you want to delete this Question</h1>
<h2>{{post.question | safe}}</h2>
<form method="post">
  {% csrf_token %}
  <button class="btn btn-outline-danger">Delete</button>
</form>
{% else %}
<h1>you don't have permission for this page</h1>
{% endif %} {% endblock sidebar %}

stack/templates/feed.html
{% extends 'sidebar.html' %}{% load static %} {% block sidebar %}
<link rel="stylesheet" href="{% static 'css/feed.css' %}" />
<main>
  {% for x in questions %}
  <section class="questions">
    <h3>{{x.user.username}}</h3>
    <p>{{x.question | safe}}</p>
    <a href="{% url 'stack:comments' x.id %}">view answers</a>
  </section>
  <hr style="color: white" />
  {% endfor %}
</main>
{% endblock sidebar %}

stack/templates/sidebar.html
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/sidebar.css' %}"
    />
    <title>{{title}}</title>
  </head>
  <body>
    <div class="container">
      <div class="sidebar-active">
        <div class="side_links">
          <li>
            <a href="{% url 'stack:feed' %}"><strong>Feed</strong></a>
          </li>
          <li>
            <a href="{% url 'stack:ask' %}"><strong>Ask</strong></a>
          </li>
          <li>
            <a href="{% url 'stack:posts' %}"><strong>Your posts</strong></a>
          </li>
        </div>
        <div class="bottom_links">
          <form method="post">
            {% csrf_token %}
            <button name="logout" class="btn btn-danger">
              <strong>Logout</strong>
            </button>
          </form>
        </div>
      </div>
      <div class="content">{% block sidebar %} {% endblock sidebar %}</div>
    </div>
  </body>
</html>

stack/templates/user_posts.html
{% extends 'sidebar.html' %} {% block sidebar %} {% load static %}
<link rel="stylesheet" href="{% static '/css/posts.css' %}" />
<main>
  {% for x in questions %}
  <section>
    <h4>
      {{x.question | safe}}
      <a
        class="btn btn-outline-danger btn-sm"
        href="{% url 'stack:delete' x.pk %}"
        >delete</a
      >
    </h4>
    <a href="{% url 'stack:comments' x.id %}">View Answers</a>
  </section>
  {% endfor %}
</main>
{% endblock sidebar %}

stack/templates/view_comment.html
{% extends 'sidebar.html' %} {% block sidebar %} {% load static %}

<link rel="stylesheet" href="{% static '/css/view_comment.css' %}" />
<main>
  {% if not answers %}
  <h1>There is no answers</h1>
  {% endif %} {% for x in answers %}
  <div class="answers">
    <h1>{{x.posted_by}}</h1>
    <p>{{x.answer | safe }}</p>
  </div>
  {% endfor %} {% if asked != user %}
  <form method="post">
    {% csrf_token %} {{form.media}} {{form.as_p}}
    <button class="btn btn-primary">Answer</button>
  </form>
  {% endif %}
</main>
{% endblock sidebar %}